export {TingBackHeader} from '../CustomUI/CustomBackHeader/CustomBackHeader'
export {TingDefaultButton} from '../CustomUI/CustomButtons/DefaultTingButton/TingButton'
export {TingBigText} from '../CustomUI/CustomText/BigTingText'
export {TingSmallText} from '../CustomUI/CustomText/SmallTingText'
export {TingInput} from '../CustomUI/CustomTextInput/DefaultTingInput'
export {TingHeaderText} from '../CustomUI/CustomBackHeader/CustomHeaderText'
export {TingButtonBack, TingButtonNext} from '../CustomUI/IconByPlatfrom/IconByPlatfrom'